[MM-26589] Add context version to all public methods
mattermost/go-circleci pull request #2
Opened 2020-06-30 19:03 UTC by ethervoid

#### Summary

To be able to cancel the request by timeout or deadline we need to pass the context to the request.
    
This PR a new *WithContext method to all the exposed methods so the user can:

- Use the current method, which is going to create a [context.Background](https://golang.org/pkg/context/#Background) context
- Use the *WithContext method and pass their own context

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-26589

2020-06-30 19:04 UTC, ethervoid commented
@agnivade given that by now I don't have permission to assign reviews I summon you!

2020-07-01 03:15 UTC, agnivade requested changes
Just a small thing. Looks good otherwise.

2020-07-01 03:15 UTC, agnivade commented on circleci_test.go
> +	if !strings.Contains(err.Error(), "context deadline exceeded") {
We can use `errors.As(err, &context.DeadlineExceeded)`

2020-07-01 03:15 UTC, agnivade commented on circleci_test.go
> +	if err == nil || !strings.Contains(err.Error(), "context deadline exceeded") {
Same as above.

2020-07-01 14:42 UTC, closed without merging

2020-07-01 14:48 UTC, ethervoid commented
Don't know how this was closed :scream: